### ISSUE TITLE
Auto login does not work

### ISSUE THREAD

**Issue by jonaslorander** [mattiasrunge/MURRiX#110]
I've ticked the auto sign in checkbox during login, but when visiting MURRiX at a later time, or just refreshing the browser, does not auto sign in me.

This is the log output.

<code>Fri Nov 01 2013 08:47:52 GMT+0100 (CET)  server     DEBUG  Trying to authorize new client...
Fri Nov 01 2013 08:47:52 GMT+0100 (CET)  server     INFO   Will try to auto login jonas from cookie!
Fri Nov 01 2013 08:47:52 GMT+0100 (CET)  user       INFO   jonas logged in!
Fri Nov 01 2013 08:47:52 GMT+0100 (CET)  server     DEBUG  Authorizing session 6a641e82-0d3c-4097-8d6d-bede68ae56b1...
Fri Nov 01 2013 08:48:03 GMT+0100 (CET)  client     INFO   Client connected</code>

Apparently the auto sign in works on the server side, but not on the client side...

**Comment by mattiasrunge** [comment]
Session handling has been improved in v3 though there no longer is a "Remember me"-function.
