### ISSUE TITLE
Ta bort bilder från album

### ISSUE THREAD

**Issue by kribba** [mattiasrunge/MURRiX#66]
Jag vill kunna radera bilder. Förslagsvis att man, när man tittar på bilderna som thumbnails i ett album, kan välja ett flertal bilder genom att kryssa i en checkbox och sedan väljer man vad man vill göra med dessa bilder som t.ex. att radera dem. Bilderna får gärna med fördel en färgad ram så att det blir än tydligare vilka man har markerat. /mia

**Comment by mattiasrunge** [comment]
Man kan göra detta i organize vyn samt via terminalen
